-define(RESET, "\e[0m").
-define(BOLD_ON, "\e[1m").
-define(ITALIC_ON, "\e[3m").
-define(UNDERLINE_ON, "\e[4m"). 
-define(INVERSE_ON, "\e[7m"). 
-define(STRIKETRU_ON, "\e[9m"). 
-define(BOLD_OFF, "\e[22m"). 
-define(ITALICS_OFF, "\e[23m").
-define(UNDERLINE_OFF, "\e[24m").
-define(INVERSE_OFF, "\e[27m").
-define(STRIKETRU_OFF, "\e[29m").
-define(F_BLACK, "\e[30m").
-define(F_RED, "\e[31m").
-define(F_GREEN, "\e[32m").
-define(F_YELLOW, "\e[33m").
-define(F_BLUE, "\e[34m").
-define(F_MAGENTA, "\e[35m").
-define(F_CYAN, "\e[36m").
-define(F_WHITE, "\e[37m").
-define(F_DEFAULT, "\e[39m").
-define(B_BLACK, "\e[40m").
-define(B_RED, "\e[41m").
-define(B_GREEN, "\e[42m").
-define(B_YELLOW, "\e[43m").
-define(B_BLUE, "\e[44m").
-define(B_MAGENTA, "\e[45m").
-define(B_CYAN, "\e[46m").
-define(B_WHITE, "\e[47m").
-define(B_DEFAULT, "\e[49m").
-define(bold(X), ?BOLD_ON++X++?BOLD_OFF).
-define(italic(X), ?ITALIC_ON++X++?ITALIC_OFF).
-define(with_reset(X), X++?F_DEFAULT++?B_DEFAULT).
-define(with_color(X, Color), ?with_reset(Color++X)).
-define(red(X), ?with_color(X, ?F_RED)).
-define(blue(X), ?with_color(X, ?F_BLUE)).
-define(green(X), ?with_color(X, ?F_GREEN)).
-define(default(X), ?with_color(X, ?F_DEFAULT)).
-define(yellow(X), ?with_color(X, ?F_YELLOW)).
-define(magenta(X), ?with_color(X, ?F_MAGENTA)).
-define(cyan(X), ?with_color(X, ?F_CYAN)).
-define(send(X), gen_tcp:send(Socket, X++?F_DEFAULT++"\r\n")).
-define(PROMPT, "#> ").
-define(NEWLINE, "\r\n").
